### ISSUE TITLE
[Request] Download link 

### ISSUE THREAD

**Issue by lampela** [archetyped/simple-lightbox#786] opened 2020-04-04 14:38 UTC
## Description of Problem

Download link

## Details

Would work perfectly also in press media pages if there was a download the original image link available in the lightbox.

**Comment by archetyped** [comment] 2020-04-09 23:14
Duplicate of #216 

Please add your vote and feedback to the existing ticket for this feature.

Thanks.

**Closed by archetyped** 2020-04-09 23:14 UTC
Labels: duplicate, support
