### ISSUE TITLE
[Request]: Full screen support on phones

### ISSUE THREAD

**Issue by pasta-farian** [archetyped/simple-lightbox#917] opened 2021-11-19 18:31 UTC
## Description of feature

Thank you for providing the best wordpress lightbox out there! It would be just perfect if it showed the images at full screen on phones. Might be the same as #807, but I'm making it a request rather than feedback. 
 
## This feature would be used to

Improve the user's experience on small screens. Most of my audience look at my posts on their phones. Lots of screen real state is wasted and the images are shown in too small a window. See attachment.

## If you added this feature, I would:

Eat my cat and shave my hat ;)

![signal-2021-11-19-102925](https://user-images.githubusercontent.com/64602708/142673494-1ce0dcf2-6a4e-495b-b2a6-139c6d27acb3.png)

**Comment by archetyped** [comment] 2021-11-23 22:24
Duplicate of #807.  Feedback can easily become a request.  Adding your thoughts to the existing ticket is recommended to make sure all details are in one place.

Thanks.

**Closed by archetyped** 2021-11-23 22:24 UTC
Labels: enhancement
