### ISSUE TITLE
Issue: with an empty caption field as well caption as description text of the image are shown

### ISSUE THREAD

**Issue by gjwmvg** [archetyped/simple-lightbox#711] opened 2019-02-18 05:49 UTC
In comment on #710 : 

Dear,

Yes, as describited in the SLB documentation. **But in the real world it does not work like that.** Since the last update of SLB ( V2.7.0 to 2.7.1 ) the SLB plug-in shows the wrong information !!!
Look at the 4 pictures i added.

The first picture i added is a screencapture from the WP image. NO caption filled in, but when you look in the SLB pop-up ( 2nd picture ) you see the pop-up shows the caption + Altenative text + Description

The third picture the WP image shows a filled caption AND Alternative text but the SLB pop-up ( 4th picture ) only shows the Alternative text.

I am not able to make it much clear.

**Comment by gjwmvg** [comment] 2019-02-18 20:42
To show the differences between V2.7.0 & V2.7.1 i have added below images : 
Example 1 : 
- CaptionEmpty-1-WP-image-info.png : contains WP image info ( Caption and/or Alternative text and/or Description field(s) )
- CaptionEmpty-1-V270.png : lightbox with SLB V2.7.0
- CaptionEmpty-1-V271.png : lightbox with SLB V2.7.1

Example 2 : 
- DescriptionEmpty-2-WP-image-info.png : contains WP image info ( Caption and/or Alternative text and/or Description field(s) )
- DescriptionEmpty-2-V270.png : lightbox with SLB V2.7.0
- DescriptionEmpty-2-V271.png : lightbox with SLB V2.7.1

Find the differences ( and that should not be difficult imo )
![captionempty-1-v270](https://user-images.githubusercontent.com/47701255/52975499-d6b95980-33d6-11e9-838c-62eefee4d257.png)
![captionempty-1-v271](https://user-images.githubusercontent.com/47701255/52975500-d6b95980-33d6-11e9-98e5-3337999c296b.png)
![captionempty-1-wp-image-info](https://user-images.githubusercontent.com/47701255/52975501-d751f000-33d6-11e9-9f5b-ce77509295d1.png)
![descriptionempty-2-v270](https://user-images.githubusercontent.com/47701255/52975503-d751f000-33d6-11e9-960d-98038ca30d26.png)
![descriptionempty-2-v271](https://user-images.githubusercontent.com/47701255/52975504-d751f000-33d6-11e9-9e6e-d4683a43d5dd.png)
![descriptionempty-2-wp-image-info](https://user-images.githubusercontent.com/47701255/52975505-d751f000-33d6-11e9-8139-c18c8f14ea13.png)

**Comment by gjwmvg** [comment] 2019-02-18 20:45
FYI : i have installed SLB V2.7.0 now at my webpage

**Comment by archetyped** [comment] 2019-02-19 01:41
Duplicate of #710 

Please add related comments to the existing issue rather than creating a new ticket, as it can make the details more difficult to track.

Thank you.

**Closed by archetyped** 2019-02-19 01:41 UTC
Labels: duplicate
