### ISSUE TITLE
Image not opening in lightbox

### ISSUE THREAD

**Issue by StuBlack5000** [archetyped/simple-lightbox#860] opened 2021-01-20 16:24 UTC
The lightbox was working fine for a long time, but all of a sudden won't open images anymore. Nothing has changed on my website. I click on the image and it basically refreshes the page or something. Checked all settings, reset the plugin, deactivated and reactivated, etc. Have latest version 2.8.1 (as of this writing). I have dozens of posts with galleries but I'm linking the latest below. 

## Details

* URL of Page exhibiting problem: https://homestudiobasics.com/topping-a50s-d50s-review/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Microsoft Edge exhibit the same problem. I don't run any other browsers.
* Version of SLB Installed: 2.8.1
* Other plugins installed: AAWP, Ad inserter, ads.text admin, All in one SEO, Attachment pages re-direct, BackWPup, Classic Editor, Compact Audio Player, Contact Form 7, Elementor, Grow Social by Mediavine, Insert Headers and Footers, jquery pin it button for images, Kraken image optimizer, ninja forms, Raffle press pro, remove amazon links from rss feed, shortcodes ultimate, site kit by google, WP file manager, WP product review lite,

**Comment by archetyped** [comment] 2021-01-21 18:20
Hi, your site has multiple JavaScript errors.  These errors can stop other scripts other scripts (such as SLB) from running.  Resolving the existing JavaScript errors should allow SLB to run normally.

You can view the JS errors in your browsers developer console.  Here are [instructions for identifying the theme or plugin(s) causing the errors](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

---

It also appears that a separate lightbox is being loaded on the page.  Loading multiple lightboxes is not recommended as they can result in unexpected behavior since they both react to the same events (i.e. a user clicking on a link).

Please provide an updated link if you're still experiencing an issue with SLB once the above issues have been resolved and I would be glad to reopen this ticket and take another look.

**Closed by archetyped** 2021-01-21 18:20 UTC
Labels: scope:external, support

**Comment by StuBlack5000** [comment] 2021-01-21 18:32
Hi, thank you for your response!

I tried 2019 theme and SLB works fine. It's the Publishable Mag theme that's not compatible, but it was working fine before.

What would you suggest I do?


Stuart Charles Black

Artist, Writer, & Designer

Home Studio Basics (Main Site)<https://homestudiobasics.com>

YouTube Channel<https://youtube.com/c/HomeStudioBasics>

Portfolio Site (Artwork)<https://painterlystew.com>

Soundcloud (Music)<https://soundcloud.com/xtra-base-hitz>

"We can tell other people about, having faith.. what we had faith in. What we found important enough to fight for. It's not whether you were right or wrong, but how much faith you were willing to have. That decides the future."

-Solid Snake to Raiden - Metal Gear Solid 2: Sons of Liberty (2001)

________________________________

**Comment by archetyped** [comment] 2021-01-26 00:53
Hi, reporting the theme's issues to the theme's developers is highly recommended.  They would have the most knowledge about the theme itself as well as the ability to update the theme as necessary.
