### ISSUE TITLE
webp

### ISSUE THREAD

**Issue by Laser-Ulm** [archetyped/simple-lightbox#954] opened 2022-07-25 21:19 UTC
## Description of Problem

Hi!
I just found out that simple-lightbox doesn't work with webp-images in a wp gallery.
I made galleries in wordpress and they opened fullsize - but no lightbox.
Edith says: Also if there is a webp in the link.
With png and jpg no problem.

thxnrgds
Laser

## Details

* URL of Page exhibiting problem: https://ursu-shop.com/de/sonderanfertigungen/ 
                            (you have to uncomment - it's my working site and I'm tired^^)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chromium
* Version of SLB Installed: 2.8.1
* Other plugins installed: a few - but as there are no probs with other formats...

**Comment by tribal2** [comment] 2022-07-26 19:22
I have the same problem with WEBP images, you can check the gallery here:
https://clubrotariodedavid.org/2022/participamos-en-el-cuadrangular-de-voleibol-organizado-por-la-jci-de-david/

**Comment by archetyped** [comment] 2022-07-27 01:40
Duplicate of #896

Please [search for existing tickets](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) before creating new ones.

Thank you.

**Closed by archetyped** 2022-07-27 01:40 UTC
Labels: support
