### ISSUE TITLE
Remove span from item.source in theme

### ISSUE THREAD

**Issue by philippemellenger** [archetyped/simple-lightbox#973] opened 2022-10-29 00:26 UTC
## Description of Problem

Hello, currently  all values in templates item.source are wrapped with a span tag making theming impossible to use:
This issue was opened 6 years ago, has it been resolved since ?
https://github.com/archetyped/simple-lightbox/issues/464

Something like this would be awesome
`<a download href="{{item.source}}">Download</a>`

But I found that function 

`	get_tag_container: function(tag) {
		// Build element
		var attr = this.get_tag_attribute();
		return this.util.format('<span %s="%s"></span>', attr, encodeURI(tag));
	},`
	
And I didn't find a way to avoid it, it seems like a big issue of the plugin. I will most likely have to get rid of the plugin just because of that function :'(
	
If there is a way to avoid this, I would love to hear it. Thank you

Best regards,
Philippe

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment] 2022-11-03 04:23
Duplicate of #464.

A description of and reason for the implementation is provided on the original ticket.

**Closed by archetyped** 2022-11-03 04:23 UTC
Labels: support
