### ISSUE TITLE
Request: Disable google font 

### ISSUE THREAD

**Issue by katmacaus** [archetyped/simple-lightbox#659] opened 2018-05-17 00:13 UTC
## Description of feature
This plugin is loading a google font Yanone Kaffeesatz. This is unnecessary, adds to load time and doesnt match my different website themes. Would be great if you had the option to disable this google font option, letting it use my theme fonts as the font choice.

## This feature would be used to
Reduce load time and better match current wordpress theme.

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment] 2018-06-01 04:45
Duplicate of #124

**Closed by archetyped** 2018-06-01 04:45 UTC
Labels: duplicate
