### ISSUE TITLE
Lightbox interaction with Wordpress Woocommerce gallery feature

### ISSUE THREAD

**Issue by ScottPavelle** [archetyped/simple-lightbox#517] opened 2016-09-02 18:21 UTC
I wish to use lightbox to show the array of photos for each "product" displayed on my page. When you open the page, the gallery appears beneath the main photo, just as it should. But if you click on a photo, half the time you get the original photo at full size, and half the time you get a lightbox slide show. 

In the ideal world the user would have a choice about which result he/she wants. Sometimes they will want to have the photo for zooming in, while other times they will want the array. There seems to be no way to provide that choice, or even to predict which result clicking on a photo will get you.

The same thing has happened to me in both Firefox and Safari.

Any help would be greatly appreciated.

Here is a sample page from the site: http://boletes.wpamushroomclub.org/WP/product/boletus-carminipes/

Scott Pavelle

* URL of Page exhibiting problem: http://boletes.wpamushroomclub.org/WP/product/boletus-carminipes/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Safari. Others unknown.
* Version of SLB Installed: Up to date.
* Other plugins installed: Many, including Gallery Bank, but I think I am using the regular built-in Gallery feature for Wordpress/woocommerce.

**Comment by archetyped** [comment] 2016-09-02 21:12
Hi, the lightbox being displayed at that link is not SLB.  WooCommerce uses a different lightbox that is included with the plugin by default.  You can use [the WooCommerce Add-on](http://archetyped.com/lab/slb-woocommerce-beta/) to enable SLB on WooCommerce product pages.

I am closing this ticket as the issue is not related to SLB, but please let me know if you pick up the add-on and you are still experiencing an issue, and I will reopen the ticket and take another look.

Thanks.

**Closed by archetyped** 2016-09-02 21:12 UTC
Labels: scope:external, support
