### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by armandsdz** [archetyped/simple-lightbox#983] opened 2022-12-22 15:22 UTC
I would suggest that support of SVG images is being added.
It seems that currently SVG links are not treated as an image and are therefore omitted  but I had a use case where SVG graphics was expected to open in a lightbox and I suppose it's a legitimate one.

Thanks!

**Comment by archetyped** [comment] 2022-12-22 22:38
Duplicate of #687 

Please for search existing tickets before creating new ones.

Thanks.

**Closed by archetyped** 2022-12-22 22:38 UTC
Labels: duplicate, support
