### ISSUE TITLE
[Feedback]: Compatibility with PHP 7.4 and PHP8

### ISSUE THREAD

**Issue by misterngan** [archetyped/simple-lightbox#969] opened 2022-09-15 12:14 UTC
I have been using simple-lightbox on some of my Wordpress websites. It's working fine on my servers with PHP 7.3.18 

However, when it was installed on Wordpress running on PHP 7.4 and PHP 8, It'll bring down the site. 

I am running my sites with bitnami on Amazon Lightsail 

Just to let you know. Thank you. It's a plugin that makes beautiful pictures pop out. I hope you'll solve it. 
![Screen Shot 2022-09-15 at 8 12 38 PM](https://user-images.githubusercontent.com/113604526/190400650-8e97837e-e272-48a8-9668-bf652206fb63.png)

**Comment by archetyped** [comment] 2022-09-21 01:25
Duplicate of [existing ticket](https://wordpress.org/support/topic/installing-or-updating-causes-fatal-errors/).

If you experience an issue in the future, be sure to create a **Support Ticket** so that your issue can be evaluated.

**Closed by archetyped** 2022-09-21 01:25 UTC
Labels: duplicate
