### ISSUE TITLE
PHP Error Messages in Debug Mode

### ISSUE THREAD

**Issue by hjklemenz** [archetyped/simple-lightbox#1049] opened 2024-01-06 08:19 UTC
## Description of Problem

The SLB Plugin works basically perfectly, but the following error messages for the SLB plugin appear in WP debug mode: 

[06-Jan-2024 07:04:36 UTC] PHP Deprecated: Use of "parent" in callables is deprecated in /home/httpd/vhosts/hjklemenz.ch/test.whatyousee.ch/wp-content/**plugins/simple-lightbox/includes/class.options.php on line 501**

[06-Jan-2024 07:04:36 UTC] PHP Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /home/httpd/vhosts/hjklemenz.ch/test.whatyousee.ch/wp-content/**plugins/simple-lightbox/includes/class.field_type.php on line 435**

## Details
* PHP: 8.2.12, WP 6.4.2
* test.whatyousee.ch
* Firefox, Edge 
* Version of SLB Installed: Version 2.9.3 
* Other plugins installed: even all deactivated

**Comment by archetyped** [comment] 2024-01-17 19:23
Duplicate of #1038

**Closed by archetyped** 2024-01-17 19:23 UTC
Labels: duplicate, support
