### ISSUE TITLE
Request: disable body scroll when lightbox is active

### ISSUE THREAD

**Issue by leihcim** [archetyped/simple-lightbox#605] opened 2017-06-05 12:09 UTC
## Description of feature/request

Disable body scroll when lightbox is active.

## This feature would be used to

Improve the lightbox.

## If you added this feature, I would:

Be very, very greatful!

**Comment by archetyped** [comment] 2017-06-06 00:45
Duplicate of #539

**Closed by archetyped** 2017-06-06 00:45 UTC
Labels: duplicate
