### ISSUE TITLE
Simple Lightbox stopped working

### ISSUE THREAD

**Issue by dude1987** [archetyped/simple-lightbox#912] opened 2021-10-31 14:50 UTC
Dear all,

Today I noticed my website doesn't open the pictures in a lightbox as before (I don't know when it stopped working).

Simple Lightbox is enabled and it worked correctly for many months. I didn't change the lightbox config or install new plugins but I update some of them regularly. I already tried to disable other plugins, restore a previous backup and change the website theme without any success.

Here is an URL where the pictures should open in a lightbox instead of a new page: https://www.fcsaintimier.ch/galerie-photos/historique-photos-equipes/

SLB version is 2.8.1, Wordpress version is 5.8.1 and PHP version is 7.4 (I also tried with PHP 7.3 and 8.0 but same issue)
Other plugins installed (all are up-to-date): 
 - AddToAny Share Buttons
 - Advanced Editor Tools (précédemment TinyMCE Advanced)
 - Akismet Anti-Spam
 - Content Views
 - Content Views Pro
 - Custom Post Type UI
 - Data Tables Generator by Supsystic
 - Display Posts
 - Duplicator
 - Easy Responsive Tabs
 - Enhanced Media Library
 - Events Manager
 - Jetpack
 - Resize Image After Upload
 - WP Maintenance Mode
 - WPForms Lite

Thanks in advance for your help.
Mika

**Comment by archetyped** [comment] 2021-11-04 00:44
Hi, this appears to be a duplicate of #906, where the lightbox's layout is not being loaded, possibly due to WordPress' outdated certificate.  Please refer to that ticket for further details and resources on resolving the issue.

Thanks.

**Closed** 2021-11-04 00:44 UTC
Labels: duplicate, support, scope:external
