### ISSUE TITLE
Issue: Both Theme lightbox and Simple Lightbox are active and visible

### ISSUE THREAD

**Issue by Miqser** [archetyped/simple-lightbox#376] opened 2015-05-21 16:32 UTC
I installed "Simple Lightbox" pluguin because it is better that the lightbox included with the Theme Trades (not a pluguin). The problem is that both are activated simultaneously, the Theme’s lightbox below and Simple Lightbox on top.
How can I disable the Theme’s lightbox (not a plugin), to see only the Simple Lightbox lightbox?
Thank you.

## Details

* URL of Page exhibiting problem: http://primercanal.com/plv-permanente/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: 2.3.1
* Other plugins installed:

**Comment by archetyped** [comment] 2015-05-23 00:11
Hi, unfortunately, SLB has no control over other lightboxes, so I would recommend contacting the theme's developer for instructions on disabling the lightbox included with the theme.

**Comment by archetyped** [comment] 2015-06-05 20:06
Closing ticket, as issue does not appear to be caused by SLB.

**Closed by archetyped** 2015-06-05 20:06 UTC
Labels: support
