### ISSUE TITLE
request: echo current showing picture URL

### ISSUE THREAD

**Issue by kimberley1111** [archetyped/simple-lightbox#648] opened 2018-03-16 07:22 UTC
A very very long time ago I asked for a request to add shortcode **{{item.url}}** to display current URL of the image that is opened to add Facebook comments under the image. Is this finally added? 

**{{item.url}}** = URL of current image (https://domain.ext/images/001.jpg)

So we can manually add Facebook comments

**Comment by archetyped** [comment] 2018-04-30 21:51
Duplicate of #529

**Closed by archetyped** 2018-04-30 21:51 UTC
Labels: duplicate
