### ISSUE TITLE
Issue: Error when I activated the plugin in debug mod

### ISSUE THREAD

**Issue by madvik** [archetyped/simple-lightbox#350] opened 2015-03-04 22:21 UTC
## Description of Problem
In debug mode when I activated the plugin :
```Strict standards: Declaration of SLB_Lightbox::_options() should be compatible with SLB_Base::_options($options_config = NULL) in D:\wamp\www\wordpress\wp-content\plugins\simple-lightbox\controller.php on line 7```

``` Strict standards: Only variables should be assigned by reference in D:\wamp\www\wordpress\wp-content\plugins\simple-lightbox\includes\class.utilities.php on line 623```

```Strict standards: Only variables should be assigned by reference in D:\wamp\www\wordpress\wp-content\plugins\simple-lightbox\includes\class.field_base.php on line 538```

``` Strict standards: Only variables should be assigned by reference in D:\wamp\www\wordpress\wp-content\plugins\simple-lightbox\includes\class.field_collection.php on line 543```

etc. x50

## Details
* Firefox
* PHP 5.4
* WordPress 4.1.1

**Comment by archetyped** [comment] 2015-03-06 00:22
Duplicate of #56

**Closed by archetyped** 2015-03-06 00:22 UTC
Labels: duplicate
