### ISSUE TITLE
Issue: Multilingual page

### ISSUE THREAD

**Issue by ErikPK10** [archetyped/simple-lightbox#725] opened 2019-05-07 07:45 UTC
## Description of Problem
The plugin does not work with a multilingual page. when using an url such as http://{baseurl}/nl/over-ons/ the simple light box is nog loaded

## Details

* URL of Page exhibiting problem:  www.gipsyadventures.nl
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Ecosia, chrome
* Version of SLB Installed: latest
* Other plugins installed: WPGlobus

**Comment by archetyped** [comment] 2019-05-14 00:18
Hi, please see [the existing ticket on SLB's multilingual support](https://github.com/archetyped/simple-lightbox/issues/205) to add your feedback on what multilingual plugin you would like to be supported in SLB via an add-on.

Thanks.

**Comment by archetyped** [comment] 2019-05-14 00:19
Duplicate of #205

**Closed by archetyped** 2019-05-14 00:18 UTC
