### ISSUE TITLE
[Request]: Fit to screen/Fullsize button in viewer

### ISSUE THREAD

**Issue by qiwichupa** [archetyped/simple-lightbox#859] opened 2021-01-19 11:12 UTC
There is option in settings, but on my site there is content like photo galleries and also single photos of documents for example. So in some situations it will be cool to give user ability to see image in non-default mode.

**Comment by archetyped** [comment] 2021-01-19 22:47
Duplicate of #764

Please add your notes to the existing ticket and vote on it (add 👍 to first post) to help development get prioritized.

Thanks.

**Closed by archetyped** 2021-01-19 22:47 UTC
Labels: enhancement
