### ISSUE TITLE
Issue: Simple Lightbox in Gallery

### ISSUE THREAD

**Issue by MushroomInternet** [archetyped/simple-lightbox#521] opened 2016-09-07 16:30 UTC
## Description of Problem

Hi,

I am trying to add the Simple Lightbox to a Wordpress Gallery but linking the images back to their files is not activating the lightbox effect. Can you please help?

Kind regards,
Andrew

## Details

* URL of Page exhibiting problem: http://aetee.milserver.co.uk/folding-gluing/omnifold-3000/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment] 2016-09-10 07:31
Hi, what plugin/theme is adding the tabbed content functionality that the gallery is placed in?  Please provide a link and I will take a look to see if there are any compatibility issues.

**Comment by MushroomInternet** [comment] 2016-09-12 08:17
Hi,


The plugin I am using to add the tabbed content is Page Builder (Beaver Builder). An example of the gallery I am trying to use can be found by visiting the link below and selecting the "Photos" tab.


http://aetee.milserver.co.uk/folding-gluing/omnifold-3000/


Kind regards,

Andrew


Andrew Merrell

Website Designer


PLEASE NOTE OUR NUMBERS HAVE CHANGED



MUSHROOM INTERNET | Powerful Websites That Generate Business
Website Design + SEO Services



Tel: +44 (0)1453 357 352

www: mushroominternet.co.uk<http://mushroominternet.co.uk/>



Mushroom Internet Ltd, Hope Mill, Hope Mill Lane, Brimscombe, Stroud, Gloucestershire GL5 2SQ

Company Reg: 07939209 | VAT No: 131 3311 72



The information in this email and any attachments is confidential and may also be legally privileged. If you are not the intended recipient, you must not copy, use, or disclose that information, and you are not authorised to retain it in any form nor to re-transmit it, and you should destroy this email. The views expressed in this e-mail are those of the individual author and not necessarily those of Mushroom Internet. Prior to taking any action based upon this e-mail message you should seek appropriate confirmation of its authenticity. Although Mushroom Internet believes this e-mail and any attachments to be free of any virus or other defect which may affect your computer, it is the responsibility of the recipient to ensure that it is virus free and Mushroom Internet Ltd does not accept any responsibility for any loss or damage arising in any way from its use.


________________________________

**Comment by archetyped** [comment] 2016-09-16 03:06
Thanks.  I have contacted the developer of Beaver Builder, but as a paid plugin, it may not be possible to access this plugin to investigate further from my end.

I will update this ticket when I have more information.

**Comment by MushroomInternet** [comment] 2016-09-16 08:14
Hi,


Thank you for updating me. There is also a free version of the Beaver Builder plugin which may help for testing purposes?


Kind regards,

Andrew


Andrew Merrell

Website Designer


PLEASE NOTE OUR NUMBERS HAVE CHANGED



MUSHROOM INTERNET | Powerful Websites That Generate Business
Website Design + SEO Services



Tel: +44 (0)1453 357 352

www: mushroominternet.co.uk<http://mushroominternet.co.uk/>



Mushroom Internet Ltd, Hope Mill, Hope Mill Lane, Brimscombe, Stroud, Gloucestershire GL5 2SQ

Company Reg: 07939209 | VAT No: 131 3311 72



The information in this email and any attachments is confidential and may also be legally privileged. If you are not the intended recipient, you must not copy, use, or disclose that information, and you are not authorised to retain it in any form nor to re-transmit it, and you should destroy this email. The views expressed in this e-mail are those of the individual author and not necessarily those of Mushroom Internet. Prior to taking any action based upon this e-mail message you should seek appropriate confirmation of its authenticity. Although Mushroom Internet believes this e-mail and any attachments to be free of any virus or other defect which may affect your computer, it is the responsibility of the recipient to ensure that it is virus free and Mushroom Internet Ltd does not accept any responsibility for any loss or damage arising in any way from its use.


________________________________

**Comment by archetyped** [comment] 2016-09-20 06:28
Hi, I've tested SLB with galleries in Beaver Builder and the images were properly displayed in the lightbox.  Can you please provide more details on how the page was built (e.g. what Beaver Builder modules you used, how you added the gallery the tab module, etc.).

Also, it appears that the gallery is no longer present at the link you provided.  Please update the page or provide a different link that exhibits the issue you are experiencing so that I can continue to investigate your issue.

Thanks.

**Comment by MushroomInternet** [comment] 2016-09-20 08:22
Hi,


I had the images placed inside the tabs module which I don't believe is available in the free version of Beaver Builder. I have set you up a user to the live site which has a premium version of Beaver Builder and have created a test page with the tabs module I was using (the gallery can be found under the Photos tab). The login details and test page URL are as follows:


Username:

lightbox

Password:

bR7NekUspe

Test Page URL:

http://aetee.com/test-page/


Hopefully this helps. I would prefer if the plugins were not disabled as this site is live but I also understand that this may be necessary for testing purposes so if you could enable them as soon as possible afterwards I would be most grateful.


Kind regards,

Andrew


Andrew Merrell

Website Designer


PLEASE NOTE OUR NUMBERS HAVE CHANGED



MUSHROOM INTERNET | Powerful Websites That Generate Business
Website Design + SEO Services



Tel: +44 (0)1453 357 352

www: mushroominternet.co.uk<http://mushroominternet.co.uk/>



Mushroom Internet Ltd, Hope Mill, Hope Mill Lane, Brimscombe, Stroud, Gloucestershire GL5 2SQ

Company Reg: 07939209 | VAT No: 131 3311 72



The information in this email and any attachments is confidential and may also be legally privileged. If you are not the intended recipient, you must not copy, use, or disclose that information, and you are not authorised to retain it in any form nor to re-transmit it, and you should destroy this email. The views expressed in this e-mail are those of the individual author and not necessarily those of Mushroom Internet. Prior to taking any action based upon this e-mail message you should seek appropriate confirmation of its authenticity. Although Mushroom Internet believes this e-mail and any attachments to be free of any virus or other defect which may affect your computer, it is the responsibility of the recipient to ensure that it is virus free and Mushroom Internet Ltd does not accept any responsibility for any loss or damage arising in any way from its use.


________________________________

**Comment by archetyped** [comment] 2016-09-20 08:43
Please be careful about posting login information in a public forum.  I have edited your post and removed the login details, but you should delete the user to be safe.

The plugin's developers have provided the standard version of the plugin for testing, but no issues were found when using the tab module and adding a gallery to one of the tabs.

There may be a conflict specific to your site.  You can send login details to support@archetyped.com.

**Comment by archetyped** [comment] 2016-09-22 01:55
Thank you for the test page. After evaluating the page, it appears that the is caused by the Collapse-O-Matic plugin's "Content Filter" option.  When this option is enabled, it stops all other plugins that use the `the_content` filter hook (including SLB) from any further processing.

The issue has been reported to Collapse-O-Matic's developers, so hopefully this will be fixed in a timely manner.  In the meantime, unchecking the "Content Filter" option (or removing the `[expand]` shortcode from the page's content) should allow SLB (and other plugins that process the page's content) to function normally.

**Closed by archetyped** 2016-09-22 01:55 UTC
Labels: compatibility, scope:external, support
