### ISSUE TITLE
Issue: after redirect to https lightbox shows http images

### ISSUE THREAD

**Issue by tomcruise624** [archetyped/simple-lightbox#559] opened 2017-01-08 04:23 UTC
## Description of Problem

I`ve redirect everything to https by using htaccess code, the images shows as https, but when i click to display image with lightbot it make a padlock and the images shows http.

## Details

ex. url : https://www.decorationy.com/interior-design/bathroom/before-and-after-bathroom-remodel-ideas

Browsers: Firefox, Chrome

Regards,
Dev

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment] 2017-01-08 20:36
Closing. Duplicate of #558

**Closed by archetyped** 2017-01-08 20:36 UTC
Labels: duplicate
