### ISSUE TITLE
Tons of "Strict Standards" warnings on PHP 5.4+ in WP_DEBUG mode

### ISSUE THREAD

**Issue by tometzky** [archetyped/simple-lightbox#324] opened 2015-01-13 10:15 UTC
PHP 5.4 enabled "Strict Standards" by default (E_STRICT is included in E_ALL, which is enabled with WP_DEBUG). This causes lots of warnings generated with every page view:

    PHP Strict Standards:
    Declaration of SLB_Content_Handlers::get() should be compatible with SLB_Base_Collection::get($args = NULL) in /wordpress/wp-content/plugins/simple-lightbox/includes/class.content_handlers.php on line 281
    Declaration of SLB_Lightbox::_options() should be compatible with SLB_Base::_options($options_config = NULL) in /wordpress/wp-content/plugins/simple-lightbox/controller.php on line 7
    Declaration of SLB_Themes::_options() should be compatible with SLB_Base::_options($options_config = NULL) in /wordpress/wp-content/plugins/simple-lightbox/includes/class.themes.php on line 9
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 543
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.options.php on line 136
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.options.php on line 445
    Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623

This is so bad, that when WP_DEBUG_DISPLAY is enabled then it is not possible to log in.

Please correct this code to not generate warnings in Strict Standards mode. This greatly hider development of other plugins or themes, with WP_DEBUG enabled, which is recommended for development.

Please enable WP_DEBUG, WP_DEBUG_DISPLAY and E_STRICT for a site you use for development and testing of this plugin so this warnings would be visible.

**Comment by archetyped** [comment] 2015-01-13 23:47
Duplicate of #56

**Closed by archetyped** 2015-01-13 23:47 UTC
Labels: duplicate

**Comment by primozcigler** [comment] 2015-01-29 10:20
@archetyped with all due respect, the way you closed the issue #56 issue is just wrong. Strict standards notices are there for the reason. They ensure you write good & durable code. I cannot use this plugin on local dev environment just because of these issues you have. And YOU (as everyone else who is developing themes/plugins and core) should develop with WP_DEBUG to `true` as well.

So here is my proposal: if I fix these issues and submit a pull request (which will not break anything, of course) will you accept it and merge into core?
