### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by robhob** [archetyped/simple-lightbox#355] opened 2015-03-19 11:51 UTC
## I'm receiving the following errors:
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 590
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.options.php on line 136
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 311
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
Strict Standards: Declaration of SLB_Content_Handlers::get() should be compatible with SLB_Base_Collection::get($args = NULL) in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.content_handlers.php on line 281
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Only variables should be assigned by reference in /home/qoxxomqc/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623

I've just updated to the latest version of Jetpack. The errors messages appear at the top of the page when I'm signed in as admin.

## Details

* URL of Page exhibiting problem: http://designr.co.za
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed:  2.3.1
* Other plugins installed:

**Comment by archetyped** [comment] 2015-03-20 21:08
Duplicate of #56 

Please see original ticket for more information.

**Closed by archetyped** 2015-03-20 21:08 UTC
Labels: duplicate
