### ISSUE TITLE
Simple Lightbox allows scrolling

### ISSUE THREAD

**Issue by keanja** [archetyped/simple-lightbox#961] opened 2022-08-17 08:46 UTC
## Description of Problem

Hi, I just installed the Simple Lightbox on a wordpress page and in contrast to previous installations on other sites, the overlay now is scrollable even the images is perfectly scaled to the site height.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/10218284/185075801-be047118-503b-48d2-bc37-15db7e00bf3a.png">

## Details

* URL of Page exhibiting problem: https://reisefreude-blog.de/eisberge-tour-2022
* Browser: Mac Chrome, IOS Chrome
* Version of SLB Installed:  Version 2.8.1
* Other plugins installed:  Jetpack

**Comment by archetyped** [comment] 2022-08-18 19:56
Duplicate of #539

**Closed by archetyped** 2022-08-18 19:56 UTC
Labels: duplicate, support
