### ISSUE TITLE
Simple Lightbox not support image .webp

### ISSUE THREAD

**Issue by langtuhodo** [archetyped/simple-lightbox#900] opened 2021-09-01 12:03 UTC
## Description of Problem
Simple Lightbox not support image .webp , please help me.
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment] 2021-09-03 01:48
Duplicate of #896

Please [search for existing tickets](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) before creating new ones.

Thank you.

**Closed by archetyped** 2021-09-03 01:48 UTC
Labels: support
