### ISSUE TITLE
Request: Print button

### ISSUE THREAD

**Issue by frazierdesignlq** [archetyped/simple-lightbox#668] opened 2018-07-14 15:12 UTC
## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment] 2018-08-01 23:08
Duplicate of #123 

Please add your vote for this functionality at that existing post.

Thanks.

**Closed by archetyped** 2018-08-01 23:08 UTC
Labels: duplicate
