### ISSUE TITLE
Request: Enable grouping on only gallery items.

### ISSUE THREAD

**Issue by RoxannaJoy** [archetyped/simple-lightbox#723] opened 2019-04-23 05:53 UTC
## Description of feature

**Enable grouping option to just affect gallery items only.**

_Currently:_

Group items (for displaying as a slideshow) (Default: Enabled) <- you NEED this

Group gallery items separately (Default: Disabled)  <- for this to even work

But the problem is it forces you to group absolutely everything even if you JUST want the gallery.

I want a light box, and galleries to group together, but i don't want EVERYTHING to group together;
I am using a one-page design, with my portfolio pieces that appear as pop-ups, because it groups everything together, and it is one-page, it doesn't recognize the portfolio pieces as separate entities and groups it altogether- galleries don't appear as a slideshow/grouped by default so its a pick your poison- either annoy people clicking on separate items, or have everything randomly grouped together. (yes I have _Group gallery items separately_ enabled, but it doesnt help with the single images).

## If you added this feature, I would:

a) Eat my hat
**b) Jump for joy**
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment] 2019-04-30 04:15
Duplicate of #314

**Closed by archetyped** 2019-04-30 04:15 UTC
Labels: duplicate
