### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by celestial** [archetyped/simple-lightbox#698] opened 2018-11-07 15:11 UTC
## Description of Problem

On the Google Pixel mobile phone, lightbox images open at the top of the page so the user has to scroll up to see the images. Images display properly on iPhone, iPad, and desktop (within the viewport). 

## Details

* URL of Page exhibiting problem: https://www.crenshawlighting.com/highlights/installed-fixtures-at-mn-state-capitol-building/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome on Google Pixel phone

* Version of SLB Installed: 2.7.0

* Other plugins installed: Admin Columns, Advanced Custom Fields PRO, Akismet, Enable Media Replace, Enhanced Media Library PRO, Google Analytics for WordPress by MonsterInsights, Gravity Forms, Gravity Forms MailChimp Add-On, Redirection, Responsive Menu Pro, Search & Filter Pro, SearchWP, Tablepress, WPOptimize, Yoast

**Comment by archetyped** [comment] 2018-11-08 00:59
Hi, the page at the link provided appears to have some invalid HTML or CSS that is preventing Chrome from being able to determine the position in the viewport.  This may be caused by the active theme or another plugin.  See SLB's documentation for [instructions on identifying conflicting themes/plugins](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Validation results:

* [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.crenshawlighting.com%2Fhighlights%2Finstalled-fixtures-at-mn-state-capitol-building%2F)
* [CSS validation errors](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.crenshawlighting.com%2Fhighlights%2Finstalled-fixtures-at-mn-state-capitol-building%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)

Once you have identified the conflict, it is recommended that you contact the theme/plugin developer to get the issue resolved.  Please also leave a comment here with the name and link of the conflicting theme or plugin and I would be glad to take a look to see if anything can be done from SLB's end.

This ticket is being closed as the issue is not directly related to SLB.  If you are still experiencing the same issue with SLB once the conflict has been resolved, please provide updated details, and I would be glad to reopen the ticket and take another look.

**Closed by archetyped** 2018-11-08 00:59 UTC
Labels: compatibility, scope:external, support
