### ISSUE TITLE
Vertical position of lightbox on mobile

### ISSUE THREAD

**Issue by powelli** [archetyped/simple-lightbox#934] opened 2022-02-24 00:45 UTC
## Description of Problem

When viewing images in the lightbox on a mobile device, the lightbox is positioned flush against the top of the browser window. This makes for a poor user experience as:
- The user needs to reposition the hand to reach the top of the screen, tricky on todays larger mobile devices
- Cycling through images of differing aspect ratios means moving your hand/thumb repeatedly to reach the image to tap

## Details

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Android
* Version of SLB Installed: 2.8.1

**Comment by archetyped** [comment] 2022-02-25 18:39
Duplicate of #512

**Closed by archetyped** 2022-02-25 18:39 UTC
Labels: duplicate, support
