### ISSUE TITLE
Manual activation on html page

### ISSUE THREAD

**Issue by andreascarfo** [archetyped/simple-lightbox#857] opened 2021-01-16 15:20 UTC
I replicate [this](https://github.com/archetyped/simple-lightbox/issues/856) issue as I didn't solved my problem and documentation is not so clear to me as I have to put manual activation in a html page.

Thanks

On a homepage I'm inserting some photos out frome the main content
and I'd like those photos to open in a lightbox.
I tryed to replicate the same code inside the main container of the page and the lightbox would work there.
But I would need to use more sections.

I enabled all options in "activation" options.
Details

    https://www.erraredesign.it/front-page/
    Both Firefox and Chrome
    SLB Installed: 2.8.1
    Other plugins installed: I tryed to disable all the unnecessary ones, so I kept active only: Gantry (my framework)
    Anyway these are my plugins:

    Akismet
    Campi Personalizzati Avanzati
    Classic Editor
    Enable jQuery Migrate Helper
    Gantry 5 Framework
    Get Custom Field Values
    heatmap for WordPress
    HTML Editor Syntax Highlighter
    Meow Gallery
    Post Slider and Carousel with Widget
    SG Optimizer
    Simple LightboxSettings
    Smash Balloon Instagram Feed
    Visual Editor Custom Buttons

**Comment by archetyped** [comment] 2021-01-19 21:59
Duplicate of #856

**Closed by archetyped** 2021-01-19 21:59 UTC
Labels: support
