### ISSUE TITLE
[Request]: Enable/Disable on Specific Post/Page

### ISSUE THREAD

**Issue by Tabbinski** [archetyped/simple-lightbox#1087] opened 2024-09-30 22:56 UTC
## Description of feature

It would be cool if there was a way to deactivate Simple Lightbox on select pages or posts by inputting page/post ID# in an exceptions box. 

## This feature would be used to

I have SLB deployed sitewide and it works great to zoom images as needed. I also have Envira Gallery deployed on a single page. It would be nice if I could make an exception for that one page as both lightboxes open on click. It's not a big deal and I'll still shave my cat if you don't implement it but it would be a handy additional feature,

## If you added this feature, I would:

a) Shave my hat
b) Joy for jump
c) Eat my cat
d) **Some of the above**

**Comment by archetyped** [comment] 2024-10-04 18:07
Duplicate of #272 - best to add your vote and comments to the existing post to keep all discussion in one place.

In the meantime, you can use the `[slb_exclude]` shortcode to exclude any part of a post's/page's content (such as a gallery).  See [SLB's Shortcodes documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude) for more details.

**Closed by archetyped** 2024-10-04 18:07 UTC
Labels: enhancement
