### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by webzunft** [archetyped/simple-lightbox#356] opened 2015-03-21 15:12 UTC
Simple Lightbox throws over 100 errors when activating WP_DEBUG and therefore makes it impossible to track real errors.

Those are the messages that get repeated over and over again:
```
PHP Strict Standards:  Declaration of SLB_Lightbox::_options() should be compatible with SLB_Base::_options($options_config = NULL) in /wordpress/wp-content/plugins/simple-lightbox/controller.php on line 7
PHP Strict Standards:  Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
PHP Strict Standards:  Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 538
PHP Strict Standards:  Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.field_collection.php on line 543
PHP Strict Standards:  Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.options.php on line 445
```

**Comment by archetyped** [comment] 2015-03-24 01:33
Duplicate of #56

Please see original ticket for more information.

**Closed by archetyped** 2015-03-24 01:33 UTC
Labels: duplicate
