### ISSUE TITLE
Issue: images not resizing

### ISSUE THREAD

**Issue by kamishiro** [archetyped/simple-lightbox#656] opened 2018-04-30 13:02 UTC
## Description of Problem

Just noticed an issue with the images on http://halfpennydreadfuls.com not resizing to fit (not even loading in the middle of the screen). Happens in all three browsers: Firefox, Chrome, Opera.
Doesn't seem to be a conflict with theme or plugins (tried disabling, even reset/deleted/reinstalling the lightbox plugin) as I'm using the same theme/plugin combinations other places the plugin works flawlessly.
Any ideas would be appreciated...

## Details

* URL of Page exhibiting problem: http://halfpennydreadfuls.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by kamishiro** [comment] 2018-04-30 13:05
(Sorry - was trying to search, posted instead)
Just noticed an issue with the images on http://halfpennydreadfuls.com not resizing to fit (not even loading in the middle of the screen). Doesn't seem to be a conflict with theme or plugins (tried disabling, even reset/deleted/reinstalling the lightbox plugin) as I'm using the same theme/plugin combinations other places the plugin works flawlessly.
Any ideas would be appreciated...

**Comment by archetyped** [comment] 2018-04-30 20:34
Hi, this issue is usually caused by invalid HTML that prevents the browser from being able to accurately determine the height of the window.  Temporarily switching to one of WordPress' default themes (e.g. Twenty Seventeen, etc.) and testing SLB's functionality is a good way to confirm whether the theme is causing the invalid HTML, or if it is a plugin.  If the issue persists with a default theme, then identifying the plugin can be done using these instructions: [Identifying plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Resolving the invalid HTML ([HTML validation results here](http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Fhalfpennydreadfuls.com%2F)) is recommended to allow the browser to properly parse the page.

If you are still experiencing this issue after resolving the invalid HTML, then please leave a comment below with additional details, and I would be glad to reopen the ticket and take another look.

**Closed by archetyped** 2018-04-30 20:34 UTC
Labels: scope:external, support

**Comment by kamishiro** [comment] 2018-05-01 03:02
It was something odd in the theme (the theme itself is generally OK, but something must have broken here). Changed the,e and all is well...thanks.
