### ISSUE TITLE
Request: Print

### ISSUE THREAD

**Issue by freddymx** [archetyped/simple-lightbox#739] opened 2019-08-05 13:12 UTC
## Description of feature

print button like: http://sandbox.tse-webdesign.be/lightbox-print/

## This feature would be used to

print images

## If you added this feature, I would:
d
a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment] 2019-08-10 00:09
Duplicate of #123 

Please add your vote and feedback for this functionality at that existing post.

Thanks.

**Closed by archetyped** 2019-08-10 00:09 UTC
Labels: duplicate
