### ISSUE TITLE
Formatting of Images using Simple Lightbox v2.8.1

### ISSUE THREAD

**Issue by wholemilklatte** [archetyped/simple-lightbox#899] opened 2021-08-27 19:07 UTC
## Description of Problem

The functionality of the plugin appears to work as it should but when i click on an image to open the lightbox view it opens at the very bottom of the screen (out of view so you have to scroll down to see it), when you navigate to the next image it appears below the first image (so you again have to scroll down an entire screen's height to see the image), same behavior for subsequent images. Otherwise the functionality and styling appears to work as it is supposed to.

## Details

* URL of Page exhibiting problem: https://www.libertythermionics.com/photos/test-post-with-gallery/ (click on gallery image to open lightbox)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Safari (latest versions)
* Version of SLB Installed: Current (v2.8.1)
* Other plugins installed: There's a relatively long list, i've been trying out a number of lightbox plugins and this is the only one that is exhibiting a problem.

**Comment by archetyped** [comment] 2021-08-31 00:28
Hi, display issues like you describe are most commonly caused by invalid HTML used by the theme or added by a plugin.  Theme issues can be confirmed by switching to a theme with valid HTML (such as Twenty Fifteen) and checking if the issue has been resolved.  Plugin issues can be identified by disabling all plugins and re-activating them one-by-one, noting the plugin that causes the issue to return.

See here for [a report on the HTML errors for the link you provided](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.libertythermionics.com%2Fphotos%2Ftest-post-with-gallery%2F).  Resolving the invalid HTML will allow the browser to correctly process the page's HTML and correctly display all elements (including the lightbox).

If you are still experiencing this issue with SLB after resolving the invalid HTML, please provide an updated link, and I would be glad to reopen this ticket and take another look.

Thanks.

**Closed by archetyped** 2021-08-31 00:28 UTC
Labels: support, scope:external
