### ISSUE TITLE
Passing null to parameter #1 simple-lightbox

### ISSUE THREAD

**Issue by shihab-fr** [archetyped/simple-lightbox#1065] opened 2024-04-16 11:44 UTC
Hi, 

## Description of Problem

after update Wp & Php to 8.1 i got this :
<html><body>

  | trim(): Passing null to parameter #1 ($string) of type string is deprecatedPlugin: Simple LightboxFile: /wp-content/plugins/simple-lightbox/includes/class.utilities.phpLine: 545
-- | --

</body>
</html>trim(): Passing null to parameter #1 ($string) of type string is deprecatedPlugin: [Simple Lightbox](http://archetyped.com/tools/simple-lightbox/)
File: [/wp-content/plugins/simple-lightbox/includes/class.utilities.php](https://bsmpaint.fr/wp-admin/plugin-editor.php?file=simple-lightbox%2Fincludes%2Fclass.utilities.php&plugin=simple-lightbox%2Fmain.php)
Line: 545
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

**Comment by archetyped** [comment] 2024-04-17 23:02
Duplicate of #1008

**Closed by archetyped** 2024-04-17 23:02 UTC
Labels: duplicate, support
