### ISSUE TITLE
Issue: first image cut on mobile device

### ISSUE THREAD

**Issue by adelaydi** [archetyped/simple-lightbox#707] opened 2019-02-09 05:22 UTC
## Description of Problem

Hi,
On **mobile device** the first image shown is always cut, i want to align it with the next ones to avoid having the head cut on the picture. It happens with all the products

## Details

* URL of Page exhibiting problem: https://www.adelaydi.com/shop/stys-coat/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all of them
* Version of SLB Installed: 2.6
* Other plugins installed: Yoast SEO Premium, YITH WooCommerce Wishlist, WPBakery Visual Composer & qTranslate-X, WooCommerce PayPal Express Checkout Gateway, WooCommerce MailChimp, 
WooCommerce Currency Switcher, Slider Revolution, qTranslate-X, Popup Maker, Loco Translate, AfterShip - WooCommerce Tracking

**Comment by archetyped** [comment] 2019-02-09 23:18
Hi, it appears that Simple Lightbox is not active at the link provided, and a different lightbox is being used. Please disable other lightboxes and let me know when SLB has been enabled on the site, and I would be glad to take another look.

Thanks.

**Comment by adelaydi** [comment] 2019-02-10 04:34
Hi, thank you for your reply, I have SLB installed on my website, i send
you screenshot,
My best 

El 10-02-2019 00:18, Archetyped escribió:

> Hi, it appears that Simple Lightbox is not active at the link provided, and a different lightbox is being used. Please disable other lightboxes and let me know when SLB has been enabled on the site, and I would be glad to take another look. 
> 
> Thanks. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Adelaydi 

Links:
------
[1]
https://github.com/archetyped/simple-lightbox/issues/707#issuecomment-462088479
[2]

**Comment by archetyped** [comment] 2019-02-11 23:08
Hi, it doesn't appear that a screenshot was attached.  You may need go to the GitHub issue page directly to upload a screenshot instead of replying via email.

I would be glad to take another look once the screenshot has been uploaded.

Thanks.

**Comment by adelaydi** [comment] 2019-02-12 06:03
Hi,
Now is it ok ?
My best

![captura de pantalla 250](https://user-images.githubusercontent.com/47469380/52615113-48a01900-2e94-11e9-80d1-d749422d5b80.png)

**Comment by adelaydi** [comment] 2019-02-12 16:46
Hi,
So what is the reason why it appears cut on mobile device ( the first image)?
My best

**Comment by archetyped** [comment] 2019-02-13 03:08
Hi, as previously-noted, SLB is not being used at the link provided due to **a different lightbox** being active on the site.  You can confirm this by deactivating SLB and testing the page to see that the other lightbox is still displaying your images.

It appears that this other lightbox may have issues with mobile devices, so disabling it to allow SLB to be used to display the images may help to resolve your issue.

I'm closing this ticket for now as the issue is not related to SLB.  Let me know if you're still experiencing an issue after disabling the other lightbox and I would be glad to reopen this ticket and take another look.

**Closed by archetyped** 2019-02-13 03:08 UTC
Labels: scope:external, support
