### ISSUE TITLE
Add the ability to block scrolling when the Lightbox is open

### ISSUE THREAD

**Issue by m0nsieurdodo** [archetyped/simple-lightbox#604] opened 2017-06-01 15:28 UTC
Hello I am not sure that it is here that it must be posted.
But I wanted to know if it was possible to add an option to disable the scrolling.
Thank you.

**Comment by archetyped** [comment] 2017-06-02 00:16
Duplicate of #539

**Closed by archetyped** 2017-06-02 00:16 UTC
Labels: duplicate
