### ISSUE TITLE
PHP Warning:  count()

### ISSUE THREAD

**Issue by lj93727** [archetyped/simple-lightbox#661] opened 2018-05-21 14:44 UTC
Error logs:

[21-May-2018 14:14:43 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/xxx/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 1411
[21-May-2018 14:14:47 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/xxx/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 1411

**Comment by archetyped** [comment] 2018-06-01 03:52
Duplicate of #646

**Closed by archetyped** 2018-06-01 03:52 UTC
Labels: duplicate
