### ISSUE TITLE
Lightbox layout is not retrieved

### ISSUE THREAD

**Issue by jinlarse** [archetyped/simple-lightbox#906] opened 2021-10-06 05:47 UTC
## Details

* URL of Page exhibiting problem: https://www.dagsturhelgeland.no/unstad/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): I have tried Chrome and safari, not working
* Version of SLB Installed: 2.8.1
* Other plugins installed: Ajax Search, Akismet Anti-spam, Autoptimize, Autoptimize CriticalCSS.com Power-Up, Google Analytics for WordPress by MonsterInsights, Klassisk redigering, Kontaktskjema 7, Simple Lightbox, The SEO Framework, WP Super Cache

**Comment by BenTalagan** [comment] 2021-10-06 10:08
Seeing the same problem without updating anything (neither wordpress nor any plugin). Lightbox was working a few days ago, but now clicking on an image opens the image as a new file instead of showing it inside the LB. All browsers are affected (tested with Firefox, Chrome, Vivaldi, Safari).

URL of Page exhibiting problem : https://amaryan.fr/2021/09/28/illustration-des-ecailles-en-septembre/

- Host : Infomaniak, curl module is enabled for PHP (as suggested from https://wordpress.org/support/topic/plugin-stopped-working-223/)
- PHP version : 7.4
- SLB version : 2.8.1
- Wordpress version :  5.8.1

However, the plugin is working correctly on a local copy with a PHP server running locally through MAMP. On the server side, no error is displayed in the PHP server logs, so I don't have any clue how to debug this.

**Comment by BenTalagan** [comment] 2021-10-06 11:45
More info on this : 

https://wp-kama.com/note/error-making-request-wordpress

**Comment by archetyped** [comment] 2021-10-07 22:10
> I have talked my domene provider and they said cURL support is integrated in PHP with them.

As noted in [SLB's Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support), simply having cURL enabled for PHP may not be enough.  An important (and often missed) configuration detail is **enabling cURL for local requests**, which some hosts disable by default (or when performing server maintenance).  This configuration detail is often not looked into by hosting support staff, as most users with this issue have had the issue resolved by following up with the hosting provider to escalate their issue to someone more familiar with these settings.

> Maybe the plugin uses e.g. a separate list of root certificates that contain the expired X3 certificate for Let's Encrypt certificates? In this case, the plugin must make sure that it avoids it when using the curl libraries.

SLB uses WordPress' own built-in functionality for retrieving the lightbox's layout (the issue causing the lightbox not to open in this ticket).  This means that any certificate-related operations are handled by WordPress itself.  If an expired root certificate is the cause of the issue of the on your site, then reporting the issue to WordPress directly is recommended so that it can be fixed for all such operations on your site.

In the meantime, a workaround such as the one described in the [article on expired certificates](https://wp-kama.com/note/error-making-request-wordpress) shared by @BenTalagan may be a solution.

**Comment by BenTalagan** [comment] 2021-10-08 10:52
Looks like things are in the pipe on Wordpress's side :

https://core.trac.wordpress.org/ticket/54207
https://github.com/WordPress/WordPress/commit/b5f1eb9103bb3ecfda699a94df49f0df5de6c9bb

The thing to note is that it seems this bug will only affect installations where curl uses a 1.0.x install of openssl, not a 1.1.x one. As I understand it, it is due to the fact that openssl changed its way to validate trusted certificate chains, and whereas openssl 1.1.x would tolerate having a potentially expired chain if another good one were found, 1.0.x would be less tolerant.

**Comment by archetyped** [comment] 2023-05-05 22:26
Closing this as the issue causing this in WordPress' core appears to have been resolved.  If you are still experiencing this issue, updating WordPress is recommended.

**Closed by archetyped** 2023-05-05 22:26 UTC
Labels: support, theme, needs-details, scope:external
