### ISSUE TITLE
[Request]: Download link in lightbox

### ISSUE THREAD

**Issue by sumukhmonsoon** [archetyped/simple-lightbox#1034] opened 2023-10-17 06:59 UTC
## Description of feature

After getting popup there should be download button to download the image and there should be slider where other image can see which are in that page itself

## This feature would be used to

(Describe usage here)

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment] 2023-10-19 19:44
Duplicate of #216 

Please add your vote and feedback to the existing ticket for this feature.

Thanks.

**Closed by archetyped** 2023-10-19 19:44 UTC
Labels: duplicate, enhancement
