### ISSUE TITLE
Simple Lightbox not working since WP 5.5?

### ISSUE THREAD

**Issue by st8347384** [archetyped/simple-lightbox#824] opened 2020-08-31 14:06 UTC
## Description of Problem

SLB was working great for us with our theme and plugin set until we installed Wordpress 5.5. Now, clicking on a photo thumbnail within a gallery simply opens images within the browser window (rather than lightboxing). From what I've read in forums, it sounds like a lot of gallery plugins may have been affected by jQuery selector change in Wordpress 5.5. Just wanted to share in case it hadn't been reported yet and see if that was indeed the issue.

## Details

* URL of Page exhibiting problem: https://amazingamerica.com/locations/grand-canyon-national-park/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Firefox, Opera, etc.
* Version of SLB Installed: 2.8.1
* Other plugins installed: Many

**Comment by archetyped** [comment] 2020-08-31 22:32
Hi, are you sure you haven't made any other changes recently, especially to your hosting/server configuration?  The issue appears to be related to your site's cURL configuration.  If you did not make any changes yourself, you may need to contact your hosting company to see if any changes they made has affected your site's cURL configuration.

Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Let me know if you're still experiencing an issue once cURL has been enabled/configured, and I would be glad to take another look.

**Comment by st8347384** [comment] 2020-09-01 00:01
@archetyped I double checked, and cURL is indeed enabled: 7.67.0 OpenSSL/1.1.1g.

**Comment by archetyped** [comment] 2020-09-01 01:08
Please fully review the aforementioned documentation. cURL must be properly **configured** to work with WordPress, not just enabled.

As previously noted, you may need to contact your hosting provider as certain cURL settings are at the server-level.

**Comment by st8347384** [comment] 2020-09-01 12:37
@archetyped I checked with the web host, and they confirmed that cURL is enabled for both PHP and local requests. (The plugin has been working on their server for some time--it was right after WP 5.5 that it stopped working)

**Comment by archetyped** [comment] 2020-09-09 01:33
The specific reason why SLB is not working on your site is only caused when cURL is not enabled or not properly configured.  SLB has also been tested for full compatibility with WordPress 5.5.

As a result, it is very unlikely that this issue is related to WordPress 5.5 compatibility, but you can always reinstall to WordPress 5.4 to confirm this.

Unfortunately, based on reports from users, web host support will usually just report that "everything is fine" until you've elevated your ticket up to someone who is able to actually look into the specific server configuration (and knows what to look for).  Thus, as noted in the documentation, you may have to contact your hosting provider a few times to elevate your support request before it is resolved.

This ticket is being closed as the issue is not directly related to SLB (the cURL requirement is from WordPress itself). Please let me know if you have further details and I would be glad to reopen this ticket and take another look.

**Closed by archetyped** 2020-09-09 01:33 UTC
Labels: scope:external, support
