### ISSUE TITLE
Issue: removing pinterest symbol from simple lightbox

### ISSUE THREAD

**Issue by celwal** [archetyped/simple-lightbox#402] opened 2015-07-24 09:49 UTC
## Description of Problem

How to remove pinterest symbol from Simple Lightbox?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment] 2015-07-24 18:25
Hi, SLB does not add a Pinterest symbol, so it may be due to another plugin.  See this [guide on troubleshooting plugin conflicts](../wiki/Troubleshooting-Plugin-Conflicts) for instructions on finding the culprit.

This issue is being closed as it does not appear to be caused by SLB.  If you are still experiencing an issue, please fill in your issue's details and I would be glad to reopen it take another look.

**Closed by archetyped** 2015-07-24 18:25 UTC
Labels: needs-details, support
