### ISSUE TITLE
Issue: simple-lightbox with ajax loaded content

### ISSUE THREAD

**Issue by levi333ed** [archetyped/simple-lightbox#639] opened 2018-01-11 07:57 UTC
## Description of Problem
Hello!
I want use your great plugin with ajax loaded content, I know (in theory), for this need call js after the ajax loaded, but I don't know, exactly how and which file should...
 
On the internet exist many solution for this with the Easy Fancybox plugin, example if I use this:
jQuery( document ).on( 'focusin', easy_fancybox_handler );

... but these plugin slightly weak, and I want to use the simple-lightbox on my network.

So I would be very happy, if to write me, how can I solve this, I hope, be in existence a suchlike fast and easy solution what the mentioned above with the  easy_fancybox.
(And I think, if would you give this one line to your plugin's wordpress.org page, many people would like to enjoy it in the future!)

I looking forward to your reply!
Best regards!

## Details
* Version of SLB Installed: 2.6.0
* Other plugins installed: Ajax Load More by Darren Cooney

**Comment by archetyped** [comment] 2018-06-07 21:36
Duplicate of #208

**Closed by archetyped** 2018-06-07 21:36 UTC
Labels: duplicate
