### ISSUE TITLE
[Feedback]: Please add support for webp

### ISSUE THREAD

**Issue by AndrewMLeonard** [archetyped/simple-lightbox#921] opened 2021-12-06 21:40 UTC
We had a look at code in class.content_handlers.php and think you just need to add webp to line 215
We have done this in your file and it works but it will be overwritten if you provide an update

**Comment by bobbingwide** [comment] 2021-12-07 12:05
@AndrewMLeonard's  implementation was a quick and dirty workaround to the problem.
I appreciate that we could implement a filter function for `image_match`, but it's easier to change the plugin now that WordPress supports WebP files.  

See also #866 #896 and #900, specifically https://github.com/archetyped/simple-lightbox/issues/896#issuecomment-898158012

**Comment by archetyped** [comment] 2021-12-10 03:19
Duplicate of #896

**Closed by archetyped** 2021-12-10 03:19 UTC
Labels: duplicate
