### ISSUE TITLE
Recurring deprecated notice in wp-admin

### ISSUE THREAD

**Issue by EarthmanWeb** [archetyped/simple-lightbox#1078] opened 2024-07-29 00:42 UTC
## Description of Problem

Been receiving this error for a long time,  *in wp-admin* 

_(first - why is this loading in WP-Admin - isn't this a frontend plugin?!_)

```
trim(): Passing null to parameter #1 ($string) of type string is deprecated

wp-content/plugins/simple-lightbox/includes/class.utilities.php:545
```

## Details

* URL of Page exhibiting problem: 
```
/wp-admin/users.php
/wp-admin/edit.php?post_type=page
.. and many, many other wp-admin pages
```

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
`Chrome / Query Monitor`

* Version of SLB Installed: 
`* Version: 2.9.3`

* Other plugins installed: 
```
### wp-core ###

version: 6.6.1
site_language: en_US
user_language: en_US
timezone: America/Vancouver
permalink: /%category%/%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: undefined
environment_type: development
site_id: 1
site_count: 106
network_count: 1
user_count: 15904
dotorg_communication: true

### wp-plugins-active (33) ###

ACF QuickEdit Fields: version: 3.3.7, author: Jörn Lund, Auto-updates disabled
ACF User Role Field Setting: version: 4.0.2, author: John A. Huebner II, Auto-updates disabled
Advanced Custom Fields: Extended: version: 0.9.0.7, author: ACF Extended, Auto-updates disabled
Advanced Custom Fields: Relationship Multisite: version: 1.1.02 (>= ACF 5.2.7), author: Thomas Meyer, Auto-updates disabled
Advanced Custom Fields PRO: version: 6.3.4, author: WP Engine, Auto-updates disabled
Block Manager: version: 3.0.0, author: Darren Cooney, Auto-updates disabled
Block Visibility: version: 3.5.0, author: Nick Diego, Auto-updates disabled
CDN Enabler: version: 2.0.8, author: KeyCDN, Auto-updates disabled
Display Environment Type: version: 1.3.3, author: Roy Tanck, Auto-updates disabled
Enable Media Replace: version: 4.1.5, author: ShortPixel, Auto-updates disabled
Folded Pages: version: 2.2.0, author: Earthman Media - Terrance Orletsky, Auto-updates disabled
Getwid: version: 2.0.11, author: MotoPress, Auto-updates disabled
Intuitive Custom Post Order: version: 3.1.5.1, author: hijiri, Auto-updates disabled
Members: version: 3.2.9, author: MemberPress, Auto-updates disabled
MWW Scheduled Post Trigger: version: 3.2, author: Moss Web Works, Auto-updates disabled
Native PHP Sessions for WordPress: version: 1.4.3, author: Pantheon, Auto-updates disabled
Object Cache Pro: version: 1.21.2, author: Rhubarb Group, Auto-updates disabled
Pantheon Advanced Page Cache: version: 2.0.0, author: Pantheon, Auto-updates disabled
Patchstack Security: version: 2.2.13, author: Patchstack, Auto-updates disabled
Polylang Pro: version: 3.6.3, author: WP SYNTEX, Auto-updates disabled
Query Monitor: version: 3.16.4, author: John Blackbourn, Auto-updates disabled
Redirection: version: 5.4.2, author: John Godley, Auto-updates disabled
Resizable Editor Sidebar: version: 1.0.5, author: Toast Plugins, Auto-updates disabled
Rewrite Rules Inspector: version: 1.4.0, author: Automattic, Daniel Bachhuber, Auto-updates disabled
Simple Lightbox: version: 2.9.3, author: Archetyped, Auto-updates disabled
Term Management Tools: version: 2.0.1, author: theMikeD, scribu, Auto-updates disabled
Theme and plugin translation for Polylang (TTfP): version: 3.4.2, author: Marcin Kazmierski, Auto-updates disabled
User Switching: version: 1.8.0, author: John Blackbourn, Auto-updates disabled
wA11y - The Web Accessibility Toolbox: version: 1.0.3, author: Rachel Cherry, Auto-updates disabled
WordPress Multisite Content Copier/Updater: version: 2.1.6, author: Obtain Infotech, Auto-updates disabled
XML Sitemap Generator for Google: version: 4.1.21, author: Auctollo, Auto-updates disabled
XO Event Calendar: version: 3.2.10, author: Xakuro, Auto-updates disabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates disabled
```

**Comment by EarthmanWeb** [comment] 2024-07-29 00:58
@archetyped  Further debug info:

```
Debug | validate_client_object obj: (null)

Debug | validate_client_object cmd: {$.extend(SLB, {"context":["admin","admin_action_edit","admin_post-type_page","admin_page_edit","admin_page_edit_action_edit","admin_post-type_page_action_edit","user_registered"]}

```

**Comment by archetyped** [comment] 2024-08-02 23:19
Duplicate of #1038

> (first - why is this loading in WP-Admin - isn't this a frontend plugin?!)

Plugin has admin settings, hence code must be loaded in admin.

**Closed by archetyped** 2024-08-02 23:19 UTC
Labels: support
