### ISSUE TITLE
[Request]: Support WebP

### ISSUE THREAD

**Issue by idoweinberg** [archetyped/simple-lightbox#953] opened 2022-07-21 00:11 UTC
## Description of feature

Currently, my webp images do not open in the "lightbox" UI, but open in a separate page (users need to click "back" to get to the post)

## This feature would be used to

Show .webp images

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

I don't own a cat

**Comment by archetyped** [comment] 2022-07-23 00:20
Duplicate of #896

Please [search for existing tickets](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) before creating new ones.

Thank you.

**Closed by archetyped** 2022-07-23 00:20 UTC
Labels: enhancement
